ALTER TABLE mate_agent ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(500);
ALTER TABLE mate_agent ADD COLUMN IF NOT EXISTS capability_tags VARCHAR(500);
ALTER TABLE mate_agent ADD COLUMN IF NOT EXISTS agent_status VARCHAR(20) DEFAULT 'AVAILABLE';
ALTER TABLE mate_agent ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT TRUE;
