CREATE TABLE IF NOT EXISTS mate_artifact (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    message_id BIGINT,
    creator_agent_id BIGINT NOT NULL,
    workspace_id BIGINT NOT NULL,
    artifact_name VARCHAR(255) NOT NULL,
    artifact_type VARCHAR(30) NOT NULL,
    file_path VARCHAR(1000),
    current_version INT NOT NULL DEFAULT 1,
    deploy_status VARCHAR(20) NOT NULL DEFAULT 'none',
    deploy_url VARCHAR(1000),
    tags VARCHAR(500),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_art_conversation (conversation_id),
    KEY idx_art_creator (creator_agent_id),
    KEY idx_art_workspace (workspace_id),
    KEY idx_art_type (artifact_type),
    KEY idx_art_deploy (deploy_status),
    KEY idx_art_created (created_at),
    CONSTRAINT fk_art_conversation FOREIGN KEY (conversation_id) REFERENCES mate_conversation(id) ON DELETE CASCADE,
    CONSTRAINT fk_art_message FOREIGN KEY (message_id) REFERENCES mate_message(id) ON DELETE SET NULL,
    CONSTRAINT fk_art_agent FOREIGN KEY (creator_agent_id) REFERENCES mate_agent(id) ON DELETE RESTRICT,
    CONSTRAINT fk_art_workspace FOREIGN KEY (workspace_id) REFERENCES mate_workspace(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
